name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.11-bookworm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync dependencies with uv
        working-directory: app/backend
        run: uv sync --extra dev

      - name: Run backend lint
        working-directory: app/backend
        run: |
          uv run black --check src tests --line-length 100
          uv run ruff check src tests
          uv run mypy src

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.11-bookworm

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: fullstack_test
        options: >-
          --health-cmd "pg_isready -U test -d fullstack_test"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 3
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync dependencies with uv
        working-directory: app/backend
        run: uv sync --extra dev

      - name: Run backend tests
        working-directory: app/backend
        env:
          DATABASE_URL: postgresql+asyncpg://test:test@postgres:5432/fullstack_test
        run: uv run pytest -v
