name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.11-bookworm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync dependencies with uv
        working-directory: app/backend
        run: uv sync --extra dev

      - name: Run lint
        run: uv run --project app/backend make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.11-bookworm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync dependencies with uv
        working-directory: app/backend
        run: uv sync --extra dev

      - name: Run tests
        run: uv run --project app/backend make test
